### ISSUE TITLE
Nested Field does not work on 2.1.8

### ISSUE THREAD

**Issue by vinta** [encode/django-rest-framework#495]
after upgrade to 2.1.8 from 2.1.6

```
class UserSerializer(serializers.ModelSerializer):
    username = serializers.CharField()

    class Meta:
        model = User
        fields = ('id', 'username')

class PostSerializer(serializers.ModelSerializer):
    user = UserSerializer()
    tags = serializers.ManyRelatedField(source='tags', required=False)
    ......

    class Meta:
        model = Post
```

error: `'Post' object has no attribute 'username'`
