### ISSUE TITLE
DictField and ListField error if child is a serializer with many=True

### ISSUE THREAD

**Issue by warrd** [encode/django-rest-framework#5384]
The following example fails during the `bind` method:

```python
from rest_framework import serializers

class ChildSerializer(serializers.Serializer):
    pass

class ParentSerializer(serializers.Serializer):
    child = serializers.DictField(child=ChildSerializer(many=True))
```

Here is a partial stacktrace:

```
/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py in bind(self, field_name, parent)
    568     def bind(self, field_name, parent):
    569         super(ListSerializer, self).bind(field_name, parent)
--> 570         self.partial = self.parent.partial
    571 

AttributeError: 'DictField' object has no attribute 'partial'
```

When `many=False` this serializer works as expected.

The problem is introduced by #4222, which assumes the parent of ` ListSerializer` is a serializer instance, which would mean the field was declared on a serializer class rather than as a child argument to a `DictField` / `ListField`. Is this a fair assumption to make?

The [documentation](http://www.django-rest-framework.org/api-guide/fields/#dictfield) for `DictField` and `ListField` only mention a `Field` instance is expected for the `child` argument. `Serializer` is  a subclass of `Field` so I think it is fair to assume a serializer can be used here.

## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by carltongibson** [comment]
Hi @warrd is the issue here not with adding the `many=True`?

A ListField has a child. Let’s say it’s a CharField for example. Here what sense does the `many` add? I can’t see any. (List/Dict fields are already _many_.) 

So why are you trying to add the _many_? What are you looking for there? 

My first thought then is perhaps we need a guard raising an error if child has the `many=True`?

**Comment by NickStefan** [comment]
Just hit this as well when upgrading from 3.6.0 --> 3.6.3. 

The issue is that its raising an error that it previously did not raise :). I changed all the many=True to many=False and this did raise quite a few errors, so there definitely is at least some breaking change going on here.

**Comment by NickStefan** [comment]
> A ListField has a child. Let’s say it’s a CharField for example. Here what sense does the many add? I can’t see any. (List/Dict fields are already many.)

In our case we have definitions like this:

```
class NodeTreeSerializer(TreeSerializer):
    trees = serializers.ListField(
        child = NodeSerializer(many=True)
    )
```

which translate into roughly this:
```
{ 
   trees: [
      [<node>, <node>], 
      [<node>, <node>]
   ]
}
```

**Comment by NickStefan** [comment]
was able to get it to work by changing to this:
```
class NodeTreeSerializer(TreeSerializer):
    trees = serializers.ListField(
        child = serializers.ListField(
            child = NodeSerializer(many=True)
         )
    )
```

So my guess is that @warrd  could do this:
```
class ParentSerializer(serializers.Serializer):
    child = serializers.DictField(child=
          serializers.ListField(
                child = ChildSerializer()
          )
    )
```
still not good for a minor version bump, but workable.

**Comment by carltongibson** [comment]
@NickStefan Any chance you could git bisect this to work out where the change was introduced?

**Comment by warrd** [comment]
@NickStefan cheers for the suggestion, that's exactly what we ended up doing :)

@carltongibson I linked to where the change was introduced in my original comment, here it is  again: https://github.com/encode/django-rest-framework/pull/4222/files#diff-80f43677c94659fbd60c8687cce68eafR538

**Comment by carltongibson** [comment]
@warrd Sorry, yes. Thanks!

**Comment by josert** [comment]
Hi, same problem with DictField. I have tried with the ListField approach but getting the same error.  
Is there any date planned in the roadmap where the issue could be fixed?
Thanks in advance!
(version used 3.7.3)

**Comment by philipforget** [comment]
Dragging up a bit of an old issue here but I had this same issue recently when upgrading from an older version of drf. This was happening on a nested serializer that was re-defining only a _subset_ of it's fields as class attributes and also specifying the `fields` attribute in the `Meta` class. eg:

```python
# Throws the error documented in this issue
class SomeSerializer(serializers.ModelSerializer):
    some_many_field = SomeManySerializer(many=True)
    
    class Meta:
        model = SomeModel
        fields = ['some_many_field', 'some_other_field']
```

It hadn't been a problem in earlier versions of drf without the explicit `bind` of the parent being called. The fix for me was to include an explicit definition of the `some_other_field` as an attribute, eg:

```python
# Works
class SomeSerializer(serializers.ModelSerializer):
    some_many_field = SomeManySerializer(many=True)
    some_other_field = serializers.CharField(required=False)

    class Meta:
        model = SomeModel
        fields = ['some_many_field', 'some_other_field']
```

I haven't done a deep dive to see why this is the case.

**Comment by carltongibson** [comment]
>     self.partial = self.parent.partial

It looks like this could be addressed adding a `partial` property to `DictField`/`ListField` that proxied to the parent serialiser. A PR with test cases would be welcome.

**Comment by tomchristie** [comment]
Closing as (very) stale.
