### ISSUE TITLE
ImportError: cannot import name 'ORDER_PATTERN'

### ISSUE THREAD

**Issue by maltaesousa** [encode/django-rest-framework#7455]
Probably this changes breaks drf compatibility with Django 3.1:

https://github.com/django/django/commit/513948735b799239f3ef8c89397592445e1a0cd5#diff-112486a821c7f63d1ab955c6bb2b4db8

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

From a fresh new project, after installing rest_framework in `INSTALLED_APPS`, run:
```bash
python .\manage.py shell
```

```python
from rest_framework import filters
```
## Expected behavior

import correctly

## Actual behavior

Throws this:

```python
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Projects\drf\.venv\lib\site-packages\rest_framework\filters.py", line 11, in <module>
    from django.db.models.sql.constants import ORDER_PATTERN
ImportError: cannot import name 'ORDER_PATTERN'
```

**Comment by xordoquy** [comment]
Current DRF release is not supposed to work with Django 3.1 and master's build is currently green against Django 3.1 so I'll assume it's already fixed.
