### ISSUE TITLE
ImportError: cannot import name 'action'

### ISSUE THREAD

**Issue by elcolie** [encode/django-rest-framework#5830]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
User `Docker` as a gitlab runner.

```
image: python:3.6
services:
  - postgres:latest

stages:
  - test
  - build
  - deploy

variables:
  POSTGRES_DB: poinkdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - pwd
  - whoami
  - ls -alh
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - git config --global user.email "sarit@xx.x"
  - git config --global user.name "sarit"

test:
  stage: test
  tags:
    - poink
    - Elcolie
  variables:
    DATABASE_URL : "postgres://postgres:postgres@postgres:5432/poinkdb"
  script:
  - python -V
  - pip install -r requirements.txt
  - coverage run --source poinkbackend/ -m py.test poinkbackend/
  - coverage report
  only:
  - master
```

## Expected behavior
Be able to import `action` decorator like working on OSX 10.13.3

## Actual behavior
Unable to import decorator `action`
```bash
from rest_framework.decorators import action
E   ImportError: cannot import name 'action'
```

**Comment by tomchristie** [comment]
The import problem will be something to do with your setup, not the project itself.
I'd suggest checking your REST framework version.

**Comment by carltongibson** [comment]
`action` is unreleased, from #5705. It's in `master` but not v3.7.7.

**Comment by elcolie** [comment]
@tomchristie @carltongibson 
Oh. I found it I used to try new feature in `master` in my `pyenv` and I did not know I have to manually remove it. I though `pip install -r requirements.txt` will uninstall it for me since I have seen it uninstall the existing package before. 

New knowledge. It will uninstall only `released` package.
Thank you very much
