### ISSUE TITLE
When will Django4.2 be supported?

### ISSUE THREAD

**Issue by Yunx-x** [encode/django-rest-framework#8942]
When my newly created Django4.2 project imports DRF, the REST_FRAMEWORK configured in settings does not take effect

**Comment by auvipy** [comment]
the version was tested in CI, but not released yet. can you please try from master?

**Comment by lamuria** [comment]
Hey @auvipy don't want to put any kind of pressure but could give some raw estimation on when we should expect DRF to support Django 4.2?

**Comment by an5t** [comment]
I've updated Django from 4.1 to 4.2 in our project with DRF 3.14.0 and didn't noticed any issues so far.

**Comment by intgr** [comment]
> the new django release has some rough edges which is being ironed down.

Are there any particular issues with Django 4.2 that you are aware of?

I tried searching DRF issues and pull requests but could not find anything that seemed relevant. A cursory look at searching Django's bug tracker for "rest framework" also didn't turn up any relevant issues.

**Comment by mikolajnowak97** [comment]
Hi, i've encountered a problem after update django to 4.2: 

`django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'rest_framework.templatetags.rest_framework': cannot import name 'parse_header' from 'django.http.multipartparser'`

And as I can see in official release notes (https://docs.djangoproject.com/en/4.2/releases/4.2/):

- The undocumented django.http.multipartparser.parse_header() function is removed. Use django.utils.http.parse_header_parameters() instead.

Will this be resolved in the latest version?

**Comment by jooola** [comment]
> Will this be resolved in the latest version?

This has already been fixed https://github.com/encode/django-rest-framework/issues/8540

**Comment by mikolajnowak97** [comment]
> > Will this be resolved in the latest version?
> 
> This has already been fixed #8540

Thanks, my mistake. Reinstalling dependencies helped

**Comment by ebk46** [comment]
Anyone have an update as to when 4.2 might be officially be supported?

**Comment by auvipy** [comment]
can you guys please try DRF 3.14 with django 4.2.1 and report what is not working? when I added it to the CI nothing had to change TBH

**Comment by lunika** [comment]
Hi,
I tested the app I'm working on with Django 4.2.1 and DRF 3.14 and I don't have error anymore.
With Django 4.2.0 there was some errors but it seems they fix them in django 4.2.1 in my case.
