### ISSUE TITLE
Browsable API bug (in master)

### ISSUE THREAD

**Issue by yprez** [encode/django-rest-framework#1072]
The browsable API breaks on listview when the queryset is empty.

Git bisect says it was introduced in commit 10d386e.

Traceback:

```
'NoneType' object has no attribute 'company'

File "[...]/django/core/handlers/base.py" in get_response
  140.                     response = response.render()
File "[...]/django/template/response.py" in render
  105.             self.content = self.rendered_content
File "[...]/rest_framework/response.py" in rendered_content
  59.         ret = renderer.render(self.data, media_type, context)
File "[...]/rest_framework/renderers.py" in render
  540.         post_form = self._get_rendered_html_form(view, 'POST', request)
File "[...]/rest_framework/renderers.py" in _get_rendered_html_form
  437.             return self.get_rendered_html_form(view, method, request)
File "[...]/rest_framework/renderers.py" in get_rendered_html_form
  459.         data = serializer.data
File "[...]/rest_framework/serializers.py" in data
  506.                 self._data = self.to_native(obj)
File "[...]/rest_framework/serializers.py" in to_native
  309.             value = field.field_to_native(obj, field_name)
File "[...]/rest_framework/relations.py" in field_to_native
  266.                 pk = getattr(obj, self.source or field_name).pk
```
