### ISSUE TITLE
ImportError: cannot import name 'ugettext_lazy' in Django 4.2 (LTS) with drf_secure_token

### ISSUE THREAD

**Issue by VirajPoriya2202** [encode/django-rest-framework#9105]
Environment:

Django version: 4.2.1 (LTS)
DRF Secure Token version: 3.14.0
Python version: Python 3.8.10
Operating System: ubuntu

Steps to Reproduce:

Create a Django project or application.
Install drf_secure_token.
Configure the drf_secure_token authentication in your Django settings.
Run the application.
Observe the ImportError in the console.

Expected Behavior:
I expected that drf_secure_token would work correctly with Django 4.2 (LTS) without any ImportError issues.

Actual Behavior:
I encountered the following ImportError:

from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'

Django settings where drf_secure_token authentication is configured.
Any relevant code where you import or use ugettext_lazy.
Additional Context:
I have not made any custom changes to the Django or drf_secure_token setup, and this issue occurs when using Django 4.2 (LTS) with the latest version of drf_secure_token.

Possible Solution:
I'm not sure about the root cause of this issue, but it seems related to changes in Django 4.2 (LTS). One possible solution could be to update the usage of ugettext_lazy to use gettext_lazy instead in the affected code.

**Comment by submarcos** [comment]
It seems to be a [drf_secure_token](https://github.com/razortheory/drf-secure-token/blob/master/drf_secure_token/authentication.py#L1) problem, not DRF

**Comment by auvipy** [comment]
it is not a DRF issue.
