### ISSUE TITLE
Unable to make 3.0 and 2.4 Happy with ViewSets

### ISSUE THREAD

**Issue by cancan101** [encode/django-rest-framework#2059]
I know that the new (in 3.0) `ModelViewSet` require a `queryset` rather than `model` but the current version of 2.4 does NOT work with the `queryset`:

``` python
class TestModelViewSet3(viewsets.ModelViewSet):
    queryset = TestModel3.objects
    serializer_class = TestModel3Serializer
```

gives on 2.4.4:

```
'Manager' object has no attribute '_clone'
/Users/alex/Envs/drf24/lib/python2.7/site-packages/rest_framework/generics.py in get_queryset
            return self.queryset._clone() 
```

but it works on 3.0.

On 3.0:

``` python
class TestModelViewSet3(viewsets.ModelViewSet):
    model = TestModel3
    serializer_class = TestModel3Serializer
```

gives:

```
'TestModelViewSet3' should either include a `queryset` attribute, or override the `get_queryset()` method.
```

but works on 2.4.4.

Ideally the last version of 2.4 would handle either format.
